
FROM alpine

WORKDIR /mnt

RUN apk update
RUN apk add bash
RUN apk add python3

COPY requirements.txt /mnt/
RUN pip3 install -r /mnt/requirements.txt

#
# Copy in our AWS credentials
#
RUN mkdir /root/.aws/
COPY aws-credentials.txt /root/.aws/credentials

CMD /mnt/docker/entrypoint-2-analyze-tweets.sh


