#!/bin/bash
#
# Connect to our running Splunk container and export the password file.
#


# Errors are fatal
set -e

pushd $(dirname $0) >/dev/null

docker-compose exec furry-4-splunk /mnt/docker/export-password-file-from-splunk-from-within-docker


